version: "3"

tasks:
  grpc-plugins:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

  download:
    cmds:
      - go mod download

  add-repo:
    cmds:
      - git config --global --add safe.directory $(pwd)

  init:
    deps:
      - grpc-plugins
      - add-repo
      - download
