// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListProductsHandlerFunc turns a function with the right signature into a list products handler
type ListProductsHandlerFunc func(ListProductsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListProductsHandlerFunc) Handle(params ListProductsParams) middleware.Responder {
	return fn(params)
}

// ListProductsHandler interface for that can handle valid list products params
type ListProductsHandler interface {
	Handle(ListProductsParams) middleware.Responder
}

// NewListProducts creates a new http.Handler for the list products operation
func NewListProducts(ctx *middleware.Context, handler ListProductsHandler) *ListProducts {
	return &ListProducts{Context: ctx, Handler: handler}
}

/*
	ListProducts swagger:route GET /products products listProducts

# List products

Get a list of products
*/
type ListProducts struct {
	Context *middleware.Context
	Handler ListProductsHandler
}

func (o *ListProducts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListProductsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
