// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadFileOKCode is the HTTP code returned for type DownloadFileOK
const DownloadFileOKCode int = 200

/*
DownloadFileOK OK

swagger:response downloadFileOK
*/
type DownloadFileOK struct {
	/*

	 */
	ContentDisposition string `json:"Content-Disposition"`
	/*

	 */
	ContentType string `json:"Content-Type"`

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewDownloadFileOK creates DownloadFileOK with default headers values
func NewDownloadFileOK() *DownloadFileOK {

	return &DownloadFileOK{}
}

// WithContentDisposition adds the contentDisposition to the download file o k response
func (o *DownloadFileOK) WithContentDisposition(contentDisposition string) *DownloadFileOK {
	o.ContentDisposition = contentDisposition
	return o
}

// SetContentDisposition sets the contentDisposition to the download file o k response
func (o *DownloadFileOK) SetContentDisposition(contentDisposition string) {
	o.ContentDisposition = contentDisposition
}

// WithContentType adds the contentType to the download file o k response
func (o *DownloadFileOK) WithContentType(contentType string) *DownloadFileOK {
	o.ContentType = contentType
	return o
}

// SetContentType sets the contentType to the download file o k response
func (o *DownloadFileOK) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithPayload adds the payload to the download file o k response
func (o *DownloadFileOK) WithPayload(payload io.ReadCloser) *DownloadFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download file o k response
func (o *DownloadFileOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Content-Disposition

	contentDisposition := o.ContentDisposition
	if contentDisposition != "" {
		rw.Header().Set("Content-Disposition", contentDisposition)
	}

	// response header Content-Type

	contentType := o.ContentType
	if contentType != "" {
		rw.Header().Set("Content-Type", contentType)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DownloadFileInternalServerErrorCode is the HTTP code returned for type DownloadFileInternalServerError
const DownloadFileInternalServerErrorCode int = 500

/*
DownloadFileInternalServerError Internal Server Error

swagger:response downloadFileInternalServerError
*/
type DownloadFileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload map[string]string `json:"body,omitempty"`
}

// NewDownloadFileInternalServerError creates DownloadFileInternalServerError with default headers values
func NewDownloadFileInternalServerError() *DownloadFileInternalServerError {

	return &DownloadFileInternalServerError{}
}

// WithPayload adds the payload to the download file internal server error response
func (o *DownloadFileInternalServerError) WithPayload(payload map[string]string) *DownloadFileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download file internal server error response
func (o *DownloadFileInternalServerError) SetPayload(payload map[string]string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]string, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
