// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateProductHandlerFunc turns a function with the right signature into a create product handler
type CreateProductHandlerFunc func(CreateProductParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateProductHandlerFunc) Handle(params CreateProductParams) middleware.Responder {
	return fn(params)
}

// CreateProductHandler interface for that can handle valid create product params
type CreateProductHandler interface {
	Handle(CreateProductParams) middleware.Responder
}

// NewCreateProduct creates a new http.Handler for the create product operation
func NewCreateProduct(ctx *middleware.Context, handler CreateProductHandler) *CreateProduct {
	return &CreateProduct{Context: ctx, Handler: handler}
}

/*
	CreateProduct swagger:route POST /products products createProduct

# Create a new product

Create a new product
*/
type CreateProduct struct {
	Context *middleware.Context
	Handler CreateProductHandler
}

func (o *CreateProduct) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateProductParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
