// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"sandbox/http/swagger_generated/models"
)

// NewCreateProductParams creates a new CreateProductParams object
//
// There are no default values defined in the spec.
func NewCreateProductParams() CreateProductParams {

	return CreateProductParams{}
}

// CreateProductParams contains all the bound params for the create product operation
// typically these are obtained from a http.Request
//
// swagger:parameters CreateProduct
type CreateProductParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Product
	  Required: true
	  In: body
	*/
	Product *models.EchoExampleProduct
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateProductParams() beforehand.
func (o *CreateProductParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.EchoExampleProduct
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("product", "body", ""))
			} else {
				res = append(res, errors.NewParseError("product", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Product = &body
			}
		}
	} else {
		res = append(res, errors.Required("product", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
