# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: pwd

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: usr
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_MONGODB_URL: mongodb://usr:pwd@mongo:27017/
      ME_CONFIG_BASICAUTH: false
