// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EchoExampleProduct echo example product
//
// swagger:model echo_example.Product
type EchoExampleProduct struct {

	// content
	Content []interface{} `json:"content"`

	// id
	ID int64 `json:"id,omitempty"`

	// interest
	Interest float64 `json:"interest,omitempty"`

	// is active
	IsActive bool `json:"is_active,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this echo example product
func (m *EchoExampleProduct) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this echo example product based on context it is used
func (m *EchoExampleProduct) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EchoExampleProduct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EchoExampleProduct) UnmarshalBinary(b []byte) error {
	var res EchoExampleProduct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
