// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Echo Example API
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0
//	Contact:
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/octet-stream
//	  - application/json
//
// swagger:meta
package restapi
