// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadFileOKCode is the HTTP code returned for type DownloadFileOK
const DownloadFileOKCode int = 200

/*
DownloadFileOK OK

swagger:response downloadFileOK
*/
type DownloadFileOK struct {
}

// NewDownloadFileOK creates DownloadFileOK with default headers values
func NewDownloadFileOK() *DownloadFileOK {

	return &DownloadFileOK{}
}

// WriteResponse to the client
func (o *DownloadFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
